# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@3c2fe8c59284aae169107529dce6c78999f48956
      with:
        version: 6.10.0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'pnpm'
    - run: pnpm install
    - name: Lint
      run: pnpm lint
    - name: Unit test
      run: pnpm test:unit
